### ISSUE TITLE
Cannot add multiple transform values

### ISSUE THREAD

**Issue by jeffstahlin** [jenius/autoprefixer-stylus#38]
I have recently added autoprefixer-stylus to my gulp development environment and have noticed an issue that I can't seem to get around. The autoprefixer only uses the first transform value, rather than both of the ones I have set. 

I have the following code in my stylus sheet:

```stylus
.md-container::after
    -moz-transform scaleX(-1) rotate(135deg)
    -ms-transform scaleX(-1) rotate(135deg)
    -webkit-transform scaleX(-1) rotate(135deg)
    transform scaleX(-1) rotate(135deg)
```

and the output is as follows:

```css
.md-container::after {
    -webkit-transform: scaleX(-1) rotate(135deg);
    -webkit-transform: scaleX(-1);
    transform: scaleX(-1);
}
```

Autoprefixer is removing the second transform argument. The same happens if I just use:

```stylus
.md-container::after
    transform scaleX(-1) rotate(135deg)
```

I get

```css
.md-container::after {
    -webkit-transform: scaleX(-1);
    transform: scaleX(-1);
}
```

I have tried adding ```/* autoprefixer: off */ ``` before the css properties that I don't want to be auto prefixed but this doesn't seem to work either. (I found this disabling method on the original autoprefixer page https://github.com/postcss/autoprefixer#disabling)

The best workaround I have found so far is to do:

```stylus
.md-container::after
    transform scaleX(-1) rotate(135deg)
    -moz-transform scaleX(-1) rotate(135deg)
    -ms-transform scaleX(-1) rotate(135deg)
    -webkit-transform scaleX(-1) rotate(135deg)
```

which outputs:

```css
.md-container::after {
   -webkit-transform: scaleX(-1);
    transform: scaleX(-1);
    -moz-transform: scaleX(-1) rotate(135deg);
    -ms-transform: scaleX(-1) rotate(135deg);
    -webkit-transform: scaleX(-1) rotate(135deg);
}
```

This works in the latest Chrome and FirefoxDeveloperEdition, but it's not a clean way to do it. And if any browser relies only on the unprefixed transform, it will not have rotate() applied to it. Is there anything else that I could do to either disable the autoprefixing on that chunk of code or have both transforms applied in the output?
